# Generated by Django 3.2.13 on 2022-05-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'verbose_name': 'Actors and directors', 'verbose_name_plural': 'Actors and directors'},
        ),
    ]
